# 9 WorkFlow Analista Jr, futuro=JULIO

### 9.1 Objetivo

Presentar un workflow/pipeline completo al que los estudiantes deberán
<br>El Analista Jr corre sus scripts en la virtual manchine **desktop-jr** que tiene estas características


*   Normal, paga tarifa completa, nunca es apagada por Google
*   reside en el datacenter de Toronto, Canada
*   64 GB de memoria RAM
*   8 vCPU

## 9.3  Workflow

## Inicializacion

Esta parte se debe correr con el runtime en lenguaje **R** Ir al menu, Runtime -> Change Runtime Type -> Runtime type -> R

limpio el ambiente de R

In [1]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sat Jul 18 02:49:39 2026"

In [2]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  671158 35.9 1479355    79.1 1479355  79.1
Vcells 1242554  9.5 8388608    64.0 1978639  15.1

In [3]:
require("data.table")

if( !require("R.utils")) install.packages("R.utils")
require("R.utils")

Loading required package: data.table


Attaching package: ‘data.table’


The following object is masked from ‘package:base’:

    %notin%


Loading required package: R.utils

Loading required package: R.oo

Loading required package: R.methodsS3

R.methodsS3 v1.8.2 (2022-06-13 22:00:14 UTC) successfully loaded. See ?R.methodsS3 for help.

R.oo v1.27.1 (2025-05-02 21:00:05 UTC) successfully loaded. See ?R.oo for help.


Attaching package: ‘R.oo’


The following object is masked from ‘package:R.methodsS3’:

    throw


The following objects are masked from ‘package:methods’:

    getClasses, getMethods


The following objects are masked from ‘package:base’:

    attach, detach, load, save


R.utils v2.13.0 (2025-02-24 21:20:02 UTC) successfully loaded. See ?R.utils for help.


Attaching package: ‘R.utils’


The following object is masked from ‘package:utils’:

    timestamp


The following objects are masked from ‘package:base’:

    cat, commandArgs, getOption, isOpen, nullfile, parse, use, warnings

#### Parametros

In [4]:
PARAM <- list()
PARAM$semillas <- c(100019, 500029, 777977, 778777, 999961)

PARAM$semilla_primigenia <- PARAM$semillas[1]

PARAM$experimento <- 9115
PARAM$dataset <- "analistajr_competencia_2026.csv.gz"

#### Carpeta del Experimento

In [5]:
# carpeta de trabajo

setwd("/content/buckets/b1/exp")
experimento_folder <- paste0("WF", PARAM$experimento)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento_folder ))

### 9.3.1   Preprocesamiento del dataset

#### 9.3.1.1  DT incorporar dataset

In [6]:
# lectura del dataset
dataset <- fread(paste0("/content/datasets/", PARAM$dataset))

#### 9.3.1.2  CA  Catastrophe Analysis
Se intentan reparar las variables que para un mes están con todos los valores en cero.

El método que se utiliza es **Machine Learning** se asigna NA also valores, si ha leido bien, es la "anti imputación de valores faltantes"
<br> Usted podrá aplicar aquí otros métodos

In [7]:
if( !require("mice")) install.packages("mice", repos = "http://cran.us.r-project.org")
require("mice")

Loading required package: mice


Attaching package: ‘mice’


The following object is masked from ‘package:stats’:

    filter


The following objects are masked from ‘package:base’:

    cbind, rbind

In [8]:
# Escrito por alumnos de  Universidad Austral  Rosario

Corregir_MICE <- function(pcampo, pmeses) {

  meth <- rep("", ncol(dataset))
  names(meth) <- colnames(dataset)
  meth[names(meth) == pcampo] <- "sample"

  # llamada a mice  !
  imputacion <- mice(dataset,
    method = meth,
    maxit = 5,
    m = 1,
    seed = 7)

  tbl <- mice::complete(dataset)

  dataset[, paste0(pcampo) := ifelse(foto_mes %in% pmeses, tbl[, get(pcampo)], get(pcampo))]

}

In [9]:
Corregir_interpolar <- function(pcampo, pmeses) {

  tbl <- dataset[, list(
    "v1" = shift(get(pcampo), 1, type = "lag"),
    "v2" = shift(get(pcampo), 1, type = "lead")
  ),
  by = eval(envg$PARAM$dataset_metadata$entity_id)
  ]

  tbl[, paste0(envg$PARAM$dataset_metadata$entity_id) := NULL]
  tbl[, promedio := rowMeans(tbl, na.rm = TRUE)]

  dataset[
    ,
    paste0(pcampo) := ifelse(!(foto_mes %in% pmeses),
      get(pcampo),
      tbl$promedio
    )
  ]
}

In [10]:
AsignarNA_campomeses <- function(pcampo, pmeses) {

  if( pcampo %in% colnames( dataset ) ) {

    dataset[ foto_mes %in% pmeses, paste0(pcampo) := NA ]
  }
}

In [11]:

Corregir_atributo <- function(pcampo, pmeses, pmetodo)
{
  # si el campo no existe en el dataset, Afuera !
  if( !(pcampo %in% colnames( dataset )) )
    return( 1 )

  # llamo a la funcion especializada que corresponde
  switch( pmetodo,
    "MachineLearning"     = AsignarNA_campomeses(pcampo, pmeses),
    "EstadisticaClasica"  = Corregir_interpolar(pcampo, pmeses),
    "MICE"                = Corregir_MICE(pcampo, pmeses),
  )

  return( 0 )
}

In [12]:

Corregir_Rotas <- function(dataset, pmetodo) {
  gc(verbose= FALSE)
  cat( "inicio Corregir_Rotas()\n")
  # acomodo los errores del dataset

  Corregir_atributo("active_quarter", c(202006), pmetodo) # 1
  Corregir_atributo("internet", c(202006), pmetodo) # 2

  Corregir_atributo("mrentabilidad", c(201905, 201910, 202006), pmetodo) # 3
  Corregir_atributo("mrentabilidad_annual", c(201905, 201910, 202006), pmetodo) # 4

  Corregir_atributo("mcomisiones", c(201905, 201910, 202006), pmetodo) # 5

  Corregir_atributo("mactivos_margen", c(201905, 201910, 202006), pmetodo) # 6
  Corregir_atributo("mpasivos_margen", c(201905, 201910, 202006), pmetodo) # 7

  Corregir_atributo("mcuentas_saldo", c(202006), pmetodo) # 8

  Corregir_atributo("ctarjeta_debito_transacciones", c(202006), pmetodo) # 9

  Corregir_atributo("mautoservicio", c(202006), pmetodo) # 10

  Corregir_atributo("ctarjeta_visa_transacciones", c(202006), pmetodo) # 11
  Corregir_atributo("mtarjeta_visa_consumo", c(202006), pmetodo) # 12

  Corregir_atributo("ctarjeta_master_transacciones", c(202006), pmetodo) # 13
  Corregir_atributo("mtarjeta_master_consumo", c(202006), pmetodo) # 14

  Corregir_atributo("ctarjeta_visa_debitos_automaticos", c(201904), pmetodo) # 15
  Corregir_atributo("mttarjeta_visa_debitos_automaticos", c(201904), pmetodo) # 16

  Corregir_atributo("ccajeros_propios_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 17

  Corregir_atributo("mcajeros_propios_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 18

  Corregir_atributo("ctarjeta_visa_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 19

  Corregir_atributo("mtarjeta_visa_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 20

  Corregir_atributo("ctarjeta_master_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 21

  Corregir_atributo("mtarjeta_master_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 22

  Corregir_atributo("ccomisiones_otras", c(201905, 201910, 202006), pmetodo) # 23
  Corregir_atributo("mcomisiones_otras", c(201905, 201910, 202006), pmetodo) # 24

  Corregir_atributo("cextraccion_autoservicio", c(202006), pmetodo) # 25
  Corregir_atributo("mextraccion_autoservicio", c(202006), pmetodo) # 26

  Corregir_atributo("ccheques_depositados", c(202006), pmetodo) # 27
  Corregir_atributo("mcheques_depositados", c(202006), pmetodo) # 28
  Corregir_atributo("ccheques_emitidos", c(202006), pmetodo) # 29
  Corregir_atributo("mcheques_emitidos", c(202006), pmetodo) # 30
  Corregir_atributo("ccheques_depositados_rechazados", c(202006), pmetodo) # 31
  Corregir_atributo("mcheques_depositados_rechazados", c(202006), pmetodo) # 32
  Corregir_atributo("ccheques_emitidos_rechazados", c(202006), pmetodo) # 33
  Corregir_atributo("mcheques_emitidos_rechazados", c(202006), pmetodo) # 34

  Corregir_atributo("tcallcenter", c(202006), pmetodo) # 35
  Corregir_atributo("ccallcenter_transacciones", c(202006), pmetodo) # 36

  Corregir_atributo("thomebanking", c(202006), pmetodo) # 37
  Corregir_atributo("chomebanking_transacciones", c(201910, 202006), pmetodo) # 38

  Corregir_atributo("ccajas_transacciones", c(202006), pmetodo) # 39
  Corregir_atributo("ccajas_consultas", c(202006), pmetodo) # 40

  Corregir_atributo("ccajas_depositos", c(202006, 202105), pmetodo) # 41

  Corregir_atributo("ccajas_extracciones", c(202006), pmetodo) # 41
  Corregir_atributo("ccajas_otras", c(202006), pmetodo) # 43

  Corregir_atributo("catm_trx", c(202006), pmetodo) # 44
  Corregir_atributo("matm", c(202006), pmetodo) # 45
  Corregir_atributo("catm_trx_other", c(202006), pmetodo) # 46
  Corregir_atributo("matm_other", c(202006), pmetodo) # 47

  cat( "fin Corregir_rotas()\n")
}

In [13]:
# resuelvo el Catastrophe Analysis

setorder( dataset, numero_de_cliente, foto_mes )

PARAM$CA$metodo= "MachineLearning"

if( PARAM$CA$metodo %in% c("MachineLearning", "EstadisticaClasica", "MICE") )
  Corregir_Rotas(dataset, PARAM$CA$metodo)

inicio Corregir_Rotas()
fin Corregir_rotas()

#### 9.3.1.3  DR  Data Drifting
Se intenta corregir el data drifting, ajustando por algunos indices financieros

In [14]:
# meses que me interesan para el ajuste de variables monetarias
vfoto_mes <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105, 202106,
  202107, 202108, 202109
)

In [15]:
# los valores que siguen fueron calculados por alumnos

# momento 1.0  31-dic-2020 a las 23:59
vIPC <- c(
  1.9903030878, 1.9174403544, 1.8296186587,
  1.7728862972, 1.7212488323, 1.6776304408,
  1.6431248196, 1.5814483345, 1.4947526791,
  1.4484037589, 1.3913580777, 1.3404220402,
  1.3154288912, 1.2921698342, 1.2472681797,
  1.2300475145, 1.2118694724, 1.1881073259,
  1.1693969743, 1.1375456949, 1.1065619600,
  1.0681100000, 1.0370000000, 1.0000000000,
  0.9680542110, 0.9344152616, 0.8882274350,
  0.8532444140, 0.8251880213, 0.8003763543,
  0.7763107219, 0.7566381305, 0.7289384687
)

vdolar_blue <- c(
   39.045455,  38.402500,  41.639474,
   44.274737,  46.095455,  45.063333,
   43.983333,  54.842857,  61.059524,
   65.545455,  66.750000,  72.368421,
   77.477273,  78.191667,  82.434211,
  101.087500, 126.236842, 125.857143,
  130.782609, 133.400000, 137.954545,
  170.619048, 160.400000, 153.052632,
  157.900000, 149.380952, 143.615385,
  146.250000, 153.550000, 162.000000,
  178.478261, 180.878788, 184.357143
)

vdolar_oficial <- c(
   38.430000,  39.428000,  42.542105,
   44.354211,  46.088636,  44.955000,
   43.751429,  54.650476,  58.790000,
   61.403182,  63.012632,  63.011579,
   62.983636,  63.580556,  65.200000,
   67.872000,  70.047895,  72.520952,
   75.324286,  77.488500,  79.430909,
   83.134762,  85.484737,  88.181667,
   91.474000,  93.997778,  96.635909,
   98.526000,  99.613158, 100.619048,
  101.619048, 102.569048, 103.781818
)

vUVA <- c(
  2.001408838932958,  1.950325472789153,  1.89323032351521,
  1.8247220405493787, 1.746027787673673,  1.6871348409529485,
  1.6361678865622313, 1.5927529755859773, 1.5549162794128493,
  1.4949100586391746, 1.4197729500774545, 1.3678188186372326,
  1.3136508617223726, 1.2690535173062818, 1.2381595983200178,
  1.211656735577568,  1.1770808941405335, 1.1570338657445522,
  1.1388769475653255, 1.1156993751209352, 1.093638313080772,
  1.0657171590878205, 1.0362173587708712, 1.0,
  0.9669867858358365, 0.9323750098728378, 0.8958202912590305,
  0.8631993702994263, 0.8253893405524657, 0.7928918905364516,
  0.7666323845128089, 0.7428976357662823, 0.721615762047849
)

In [16]:
tb_indices <- as.data.table( list(
  "IPC" = vIPC,
  "dolar_blue" = vdolar_blue,
  "dolar_oficial" = vdolar_oficial,
  "UVA" = vUVA
  )
)

tb_indices[[ 'foto_mes' ]] <- vfoto_mes

tb_indices

   IPC       dolar_blue dolar_oficial UVA       foto_mes
1  1.9903031  39.04545   38.43000     2.0014088 201901
2  1.9174404  38.40250   39.42800     1.9503255 201902
3  1.8296187  41.63947   42.54210     1.8932303 201903
4  1.7728863  44.27474   44.35421     1.8247220 201904
5  1.7212488  46.09546   46.08864     1.7460278 201905
6  1.6776304  45.06333   44.95500     1.6871348 201906
7  1.6431248  43.98333   43.75143     1.6361679 201907
8  1.5814483  54.84286   54.65048     1.5927530 201908
9  1.4947527  61.05952   58.79000     1.5549163 201909
10 1.4484038  65.54546   61.40318     1.4949101 201910
11 1.3913581  66.75000   63.01263     1.4197730 201911
12 1.3404220  72.36842   63.01158     1.3678188 201912
13 1.3154289  77.47727   62.98364     1.3136509 202001
14 1.2921698  78.19167   63.58056     1.2690535 202002
15 1.2472682  82.43421   65.20000     1.2381596 202003
16 1.2300475 101.08750   67.87200     1.2116567 202004
17 1.2118695 126.23684   70.04789     1.1770809 202005
18 1.1881073 125.85714   72.52095     1.1570339 202006
19 1.1693970 130.78261   75.32429     1.1388769 202007
20 1.1375457 133.40000   77.48850     1.1156994 202008
21 1.1065620 137.95454   79.43091     1.0936383 202009
22 1.0681100 170.61905   83.13476     1.0657172 202010
23 1.0370000 160.40000   85.48474     1.0362174 202011
24 1.0000000 153.05263   88.18167     1.0000000 202012
25 0.9680542 157.90000   91.47400     0.9669868 202101
26 0.9344153 149.38095   93.99778     0.9323750 202102
27 0.8882274 143.61539   96.63591     0.8958203 202103
28 0.8532444 146.25000   98.52600     0.8631994 202104
29 0.8251880 153.55000   99.61316     0.8253893 202105
30 0.8003764 162.00000  100.61905     0.7928919 202106
31 0.7763107 178.47826  101.61905     0.7666324 202107
32 0.7566381 180.87879  102.56905     0.7428976 202108
33 0.7289385 184.35714  103.78182     0.7216158 202109

In [17]:
drift_UVA <- function(campos_monetarios) {
  cat( "inicio drift_UVA()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD * i.UVA,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_UVA()\n")
}

In [18]:
drift_dolar_oficial <- function(campos_monetarios) {
  cat( "inicio drift_dolar_oficial()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD / i.dolar_oficial,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_dolar_oficial()\n")
}

In [19]:
drift_dolar_blue <- function(campos_monetarios) {
  cat( "inicio drift_dolar_blue()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD / i.dolar_blue,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_dolar_blue()\n")
}

In [20]:
drift_deflacion <- function(campos_monetarios) {
  cat( "inicio drift_deflacion()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD * i.IPC,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_deflacion()\n")
}

In [21]:
drift_rank_simple <- function(campos_drift) {

  cat( "inicio drift_rank_simple()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[, paste0(campo, "_rank") :=
      (frank(get(campo), ties.method = "random") - 1) / (.N - 1), by = list(foto_mes)]
    dataset[, (campo) := NULL]
  }
  cat( "fin drift_rank_simple()\n")
}

In [22]:
# El cero se transforma en cero
# los positivos se rankean por su lado
# los negativos se rankean por su lado

drift_rank_cero_fijo <- function(campos_drift) {

  cat( "inicio drift_rank_cero_fijo()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[get(campo) == 0, paste0(campo, "_rank") := 0]
    dataset[get(campo) > 0, paste0(campo, "_rank") :=
      frank(get(campo), ties.method = "random") / .N, by = list(foto_mes)]

    dataset[get(campo) < 0, paste0(campo, "_rank") :=
      -frank(-get(campo), ties.method = "random") / .N, by = list(foto_mes)]
    dataset[, (campo) := NULL]
  }
  cat("\n")
  cat( "fin drift_rank_cero_fijo()\n")
}

In [23]:
drift_estandarizar <- function(campos_drift) {

  cat( "inicio drift_estandarizar()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[, paste0(campo, "_normal") :=
      (get(campo) -mean(campo, na.rm=TRUE)) / sd(get(campo), na.rm=TRUE),
      by = list(foto_mes)]

    dataset[, (campo) := NULL]
  }
  cat( "fin drift_estandarizar()\n")
}

In [24]:
# por como armé los nombres de campos,
#  estos son los campos que expresan variables monetarias
campos_monetarios <- colnames(dataset)
campos_monetarios <- campos_monetarios[campos_monetarios %like%
  "^(m|Visa_m|Master_m|vm_m)"]

campos_monetarios

 [1] "mrentabilidad"                      "mrentabilidad_annual"
 [3] "mcomisiones"                        "mactivos_margen"
 [5] "mpasivos_margen"                    "mcuenta_corriente"
 [7] "mcaja_ahorro"                       "mcuentas_saldo"
 [9] "mtarjeta_visa_consumo"              "mtarjeta_master_consumo"
[11] "mprestamos_personales"              "mpayroll"
[13] "mttarjeta_visa_debitos_automaticos" "mcomisiones_mantenimiento"
[15] "mtransferencias_recibidas"          "Master_mfinanciacion_limite"
[17] "Master_msaldototal"                 "Master_mlimitecompra"
[19] "Master_mconsumototal"               "Master_mpagominimo"
[21] "Visa_mfinanciacion_limite"          "Visa_msaldototal"
[23] "Visa_mlimitecompra"                 "Visa_mconsumototal"
[25] "Visa_mpagominimo"

In [25]:
# ejecuto el Data Drifting
setorder( dataset, numero_de_cliente, foto_mes )


PARAM$DR$metodo <- "deflacion"

switch(PARAM$DR$metodo,
  "ninguno"        = cat("No hay correccion del data drifting"),
  "rank_simple"    = drift_rank_simple(campos_monetarios),
  "rank_cero_fijo" = drift_rank_cero_fijo(campos_monetarios),
  "deflacion"      = drift_deflacion(campos_monetarios),
  "dolar_blue"     = drift_dolarblue(campos_monetarios),
  "dolar_oficial"  = drift_dolaroficial(campos_monetarios),
  "UVA"            = drift_UVA(campos_monetarios),
  "estandarizar"   = drift_estandarizar(campos_monetarios)
)

inicio drift_deflacion()
fin drift_deflacion()

In [26]:
colnames(dataset)

 [1] "numero_de_cliente"                  "foto_mes"
 [3] "internet"                           "cliente_edad"
 [5] "cliente_antiguedad"                 "mrentabilidad"
 [7] "mrentabilidad_annual"               "mcomisiones"
 [9] "mactivos_margen"                    "mpasivos_margen"
[11] "cproductos"                         "mcuenta_corriente"
[13] "mcaja_ahorro"                       "cdescubierto_preacordado"
[15] "mcuentas_saldo"                     "ctarjeta_visa"
[17] "ctarjeta_visa_transacciones"        "mtarjeta_visa_consumo"
[19] "ctarjeta_master"                    "ctarjeta_master_transacciones"
[21] "mtarjeta_master_consumo"            "cprestamos_personales"
[23] "mprestamos_personales"              "cpayroll_trx"
[25] "mpayroll"                           "mttarjeta_visa_debitos_automaticos"
[27] "ccomisiones_mantenimiento"          "mcomisiones_mantenimiento"
[29] "ccomisiones_otras"                  "mtransferencias_recibidas"
[31] "ccallcenter_transacciones"          "thomebanking"
[33] "chomebanking_transacciones"         "ctrx_quarter"
[35] "Master_status"                      "Master_mfinanciacion_limite"
[37] "Master_Fvencimiento"                "Master_msaldototal"
[39] "Master_mlimitecompra"               "Master_fultimo_cierre"
[41] "Master_fechaalta"                   "Master_mconsumototal"
[43] "Master_cconsumos"                   "Master_mpagominimo"
[45] "Visa_status"                        "Visa_mfinanciacion_limite"
[47] "Visa_Fvencimiento"                  "Visa_msaldototal"
[49] "Visa_mlimitecompra"                 "Visa_fultimo_cierre"
[51] "Visa_fechaalta"                     "Visa_mconsumototal"
[53] "Visa_cconsumos"                     "Visa_mpagominimo"
[55] "clase_ternaria"

In [ ]:
# se intenta corregir el data drifting utilizando algunos indices financieros

PCA

In [ ]:
excluir <- c("numero_de_cliente", "foto_mes", "clase_ternaria")

PCA_Reduccion <- function(pca_varianza_objetivo, pca_meses_fit) {

  cat("inicio PCA_Reduccion()\n")

  campos_pca <- setdiff(colnames(dataset), excluir)

  for (campo in campos_pca) {
    dataset[is.na(get(campo)), (campo) := 0]
  }

  datos_fit <- as.matrix(dataset[foto_mes %in% pca_meses_fit, campos_pca, with = FALSE])
  modelo_pca <- prcomp(datos_fit, center = TRUE, scale. = TRUE)

  varianza_explicada <- cumsum(modelo_pca$sdev^2) / sum(modelo_pca$sdev^2)
  n_componentes <- min(which(varianza_explicada >= pca_varianza_objetivo))

  cat("PCA: se retienen", n_componentes, "de", length(campos_pca), "variables\n")

  datos_todos <- as.matrix(dataset[, campos_pca, with = FALSE])
  componentes <- predict(modelo_pca, newdata = datos_todos)[, 1:n_componentes]

  dataset[, (campos_pca) := NULL]
  for (i in 1:n_componentes) {
    dataset[, paste0("PC", i) := componentes[, i]]
  }

  cat("fin PCA_Reduccion()\n")
}

In [ ]:
PARAM$PCA$varianza_objetivo <- 0.95
PARAM$PCA$meses_fit <- c(202101, 202102, 202103)

PCA_Reduccion(
  pca_varianza_objetivo = PARAM$PCA$varianza_objetivo,
  pca_meses_fit = PARAM$PCA$meses_fit
)

# verificacion rapida antes de seguir con el resto del notebook
ncol(dataset)
colnames(dataset)

#### 9.3.1.3  FE_intra_manual Feature Engineering intra-mes

Agrego campos nuevos dentro del mismo mes, SIN considerar la historia.

In [27]:
# esta funcion atributos presentes existe debido a que las modalidades poseen datasets con distinta cantidad de campos
atributos_presentes <- function( patributos )
{
  atributos <- unique( patributos )
  comun <- intersect( atributos, colnames(dataset) )

  return(  length( atributos ) == length( comun ) )
}

# el mes 1,2, ..12
if( atributos_presentes( c("foto_mes") ))
  dataset[, kmes := foto_mes %% 100]

# variable extraida de una tesis de maestria de Irlanda
if( atributos_presentes( c("mpayroll", "cliente_edad") ))
  dataset[, mpayroll_sobre_edad := mpayroll / cliente_edad]

In [28]:
# visualizo las columas del dataset a esta etapa
colnames(dataset)

 [1] "numero_de_cliente"                  "foto_mes"
 [3] "internet"                           "cliente_edad"
 [5] "cliente_antiguedad"                 "mrentabilidad"
 [7] "mrentabilidad_annual"               "mcomisiones"
 [9] "mactivos_margen"                    "mpasivos_margen"
[11] "cproductos"                         "mcuenta_corriente"
[13] "mcaja_ahorro"                       "cdescubierto_preacordado"
[15] "mcuentas_saldo"                     "ctarjeta_visa"
[17] "ctarjeta_visa_transacciones"        "mtarjeta_visa_consumo"
[19] "ctarjeta_master"                    "ctarjeta_master_transacciones"
[21] "mtarjeta_master_consumo"            "cprestamos_personales"
[23] "mprestamos_personales"              "cpayroll_trx"
[25] "mpayroll"                           "mttarjeta_visa_debitos_automaticos"
[27] "ccomisiones_mantenimiento"          "mcomisiones_mantenimiento"
[29] "ccomisiones_otras"                  "mtransferencias_recibidas"
[31] "ccallcenter_transacciones"          "thomebanking"
[33] "chomebanking_transacciones"         "ctrx_quarter"
[35] "Master_status"                      "Master_mfinanciacion_limite"
[37] "Master_Fvencimiento"                "Master_msaldototal"
[39] "Master_mlimitecompra"               "Master_fultimo_cierre"
[41] "Master_fechaalta"                   "Master_mconsumototal"
[43] "Master_cconsumos"                   "Master_mpagominimo"
[45] "Visa_status"                        "Visa_mfinanciacion_limite"
[47] "Visa_Fvencimiento"                  "Visa_msaldototal"
[49] "Visa_mlimitecompra"                 "Visa_fultimo_cierre"
[51] "Visa_fechaalta"                     "Visa_mconsumototal"
[53] "Visa_cconsumos"                     "Visa_mpagominimo"
[55] "clase_ternaria"                     "kmes"
[57] "mpayroll_sobre_edad"

#### 9.3.1.4  FE_rf Feature Engineering de nuevas variables a partir de hojas de Random Forest

In [ ]:
# No se implementa Feature Engineering a partir de Random Forest

#### 9.3.1.5  FEhist Feature Engineering historico

El Fature Engineering Histórico es la etapa que más aporta a la ganancia final, ya que enriquece cada registro del dataset con su historia.

Para cada campo del dataset original (*)
se crean lo siguientes campos de a partir de la historia
* lag1  lags de orden 1
* delta1  =  valor actual - lag1
* lag2  lags de orden 2
* delta2  = valor actual - lag2


(*) Excepto para los campos  <numero_de_cliente,  foto_mes,  clase_ternaria>

In [29]:
# Feature Engineering Historico

# todo es lagueable, menos la primary key y la clase
cols_lagueables <- copy( setdiff(
    colnames(dataset),
    c("numero_de_cliente", "foto_mes", "clase_ternaria")
) )

# https://rdrr.io/cran/data.table/man/shift.html

# lags de orden 1
dataset[,
    paste0(cols_lagueables, "_lag1") := shift(.SD, 1, NA, "lag"),
    by = numero_de_cliente,
    .SDcols = cols_lagueables
]

# lags de orden 2
dataset[,
    paste0(cols_lagueables, "_lag2") := shift(.SD, 2, NA, "lag"),
    by = numero_de_cliente,
    .SDcols = cols_lagueables
]

# agrego los delta lags
for (vcol in cols_lagueables)
{
    dataset[, paste0(vcol, "_delta1") := get(vcol) - get(paste0(vcol, "_lag1"))]
    dataset[, paste0(vcol, "_delta2") := get(vcol) - get(paste0(vcol, "_lag2"))]
}

Verificacion de los campos recien creados

In [30]:
ncol(dataset)
colnames(dataset)

[1] 273

  [1] "numero_de_cliente"
  [2] "foto_mes"
  [3] "internet"
  [4] "cliente_edad"
  [5] "cliente_antiguedad"
  [6] "mrentabilidad"
  [7] "mrentabilidad_annual"
  [8] "mcomisiones"
  [9] "mactivos_margen"
 [10] "mpasivos_margen"
 [11] "cproductos"
 [12] "mcuenta_corriente"
 [13] "mcaja_ahorro"
 [14] "cdescubierto_preacordado"
 [15] "mcuentas_saldo"
 [16] "ctarjeta_visa"
 [17] "ctarjeta_visa_transacciones"
 [18] "mtarjeta_visa_consumo"
 [19] "ctarjeta_master"
 [20] "ctarjeta_master_transacciones"
 [21] "mtarjeta_master_consumo"
 [22] "cprestamos_personales"
 [23] "mprestamos_personales"
 [24] "cpayroll_trx"
 [25] "mpayroll"
 [26] "mttarjeta_visa_debitos_automaticos"
 [27] "ccomisiones_mantenimiento"
 [28] "mcomisiones_mantenimiento"
 [29] "ccomisiones_otras"
 [30] "mtransferencias_recibidas"
 [31] "ccallcenter_transacciones"
 [32] "thomebanking"
 [33] "chomebanking_transacciones"
 [34] "ctrx_quarter"
 [35] "Master_status"
 [36] "Master_mfinanciacion_limite"
 [37] "Master_Fvencimiento"
 [38] "Master_msaldototal"
 [39] "Master_mlimitecompra"
 [40] "Master_fultimo_cierre"
 [41] "Master_fechaalta"
 [42] "Master_mconsumototal"
 [43] "Master_cconsumos"
 [44] "Master_mpagominimo"
 [45] "Visa_status"
 [46] "Visa_mfinanciacion_limite"
 [47] "Visa_Fvencimiento"
 [48] "Visa_msaldototal"
 [49] "Visa_mlimitecompra"
 [50] "Visa_fultimo_cierre"
 [51] "Visa_fechaalta"
 [52] "Visa_mconsumototal"
 [53] "Visa_cconsumos"
 [54] "Visa_mpagominimo"
 [55] "clase_ternaria"
 [56] "kmes"
 [57] "mpayroll_sobre_edad"
 [58] "internet_lag1"
 [59] "cliente_edad_lag1"
 [60] "cliente_antiguedad_lag1"
 [61] "mrentabilidad_lag1"
 [62] "mrentabilidad_annual_lag1"
 [63] "mcomisiones_lag1"
 [64] "mactivos_margen_lag1"
 [65] "mpasivos_margen_lag1"
 [66] "cproductos_lag1"
 [67] "mcuenta_corriente_lag1"
 [68] "mcaja_ahorro_lag1"
 [69] "cdescubierto_preacordado_lag1"
 [70] "mcuentas_saldo_lag1"
 [71] "ctarjeta_visa_lag1"
 [72] "ctarjeta_visa_transacciones_lag1"
 [73] "mtarjeta_visa_consumo_lag1"
 [74] "ctarjeta_master_lag1"
 [75] "ctarjeta_master_transacciones_lag1"
 [76] "mtarjeta_master_consumo_lag1"
 [77] "cprestamos_personales_lag1"
 [78] "mprestamos_personales_lag1"
 [79] "cpayroll_trx_lag1"
 [80] "mpayroll_lag1"
 [81] "mttarjeta_visa_debitos_automaticos_lag1"
 [82] "ccomisiones_mantenimiento_lag1"
 [83] "mcomisiones_mantenimiento_lag1"
 [84] "ccomisiones_otras_lag1"
 [85] "mtransferencias_recibidas_lag1"
 [86] "ccallcenter_transacciones_lag1"
 [87] "thomebanking_lag1"
 [88] "chomebanking_transacciones_lag1"
 [89] "ctrx_quarter_lag1"
 [90] "Master_status_lag1"
 [91] "Master_mfinanciacion_limite_lag1"
 [92] "Master_Fvencimiento_lag1"
 [93] "Master_msaldototal_lag1"
 [94] "Master_mlimitecompra_lag1"
 [95] "Master_fultimo_cierre_lag1"
 [96] "Master_fechaalta_lag1"
 [97] "Master_mconsumototal_lag1"
 [98] "Master_cconsumos_lag1"
 [99] "Master_mpagominimo_lag1"
[100] "Visa_status_lag1"
[101] "Visa_mfinanciacion_limite_lag1"
[102] "Visa_Fvencimiento_lag1"
[103] "Visa_msaldototal_lag1"
[104] "Visa_mlimitecompra_lag1"
[105] "Visa_fultimo_cierre_lag1"
[106] "Visa_fechaalta_lag1"
[107] "Visa_mconsumototal_lag1"
[108] "Visa_cconsumos_lag1"
[109] "Visa_mpagominimo_lag1"
[110] "kmes_lag1"
[111] "mpayroll_sobre_edad_lag1"
[112] "internet_lag2"
[113] "cliente_edad_lag2"
[114] "cliente_antiguedad_lag2"
[115] "mrentabilidad_lag2"
[116] "mrentabilidad_annual_lag2"
[117] "mcomisiones_lag2"
[118] "mactivos_margen_lag2"
[119] "mpasivos_margen_lag2"
[120] "cproductos_lag2"
[121] "mcuenta_corriente_lag2"
[122] "mcaja_ahorro_lag2"
[123] "cdescubierto_preacordado_lag2"
[124] "mcuentas_saldo_lag2"
[125] "ctarjeta_visa_lag2"
[126] "ctarjeta_visa_transacciones_lag2"
[127] "mtarjeta_visa_consumo_lag2"
[128] "ctarjeta_master_lag2"
[129] "ctarjeta_master_transacciones_lag2"
[130] "mtarjeta_master_consumo_lag2"
[131] "cprestamos_personales_lag2"
[132] "mprestamos_personales_lag2"
[133] "cpayroll_trx_lag2"
[134] "mpayroll_lag2"
[135] "mttarjeta_visa_debitos_automaticos_lag2"
[136] "ccomisiones_mantenimiento_lag2"
[137] "mcomisiones_mantenimiento_lag2"
[138] "ccomisiones_otras_lag2"
[139] "mtransferencias_recibidas_lag2"
[140] "ccallcenter_transacciones_lag2"
[141] "thomebanking_lag2"
[142] "chomebanking_transacciones_lag2"
[143] "ctrx_quarter_lag2"
[144] "Master_status_lag2"
[145] "Master_mfinanciacion_limite_lag2"
[146] "Master_Fvencimiento_lag2"
[147] "Master_msaldototal_lag2"
[148] "Master_mlimitecompra_lag2"
[149] "Master_fultimo_cierre_lag2"
[150] "Master_fechaalta_lag2"
[151] "Master_mconsumototal_lag2"
[152] "Master_cconsumos_lag2"
[153] "Master_mpagominimo_lag2"
[154] "Visa_status_lag2"
[155] "Visa_mfinanciacion_limite_lag2"
[156] "Visa_Fvencimiento_lag2"
[157] "Visa_msaldototal_lag2"
[158] "Visa_mlimitecompra_lag2"
[159] "Visa_fultimo_cierre_lag2"
[160] "Visa_fechaalta_lag2"
[161] "Visa_mconsumototal_lag2"
[162] "Visa_cconsumos_lag2"
[163] "Visa_mpagominimo_lag2"
[164] "kmes_lag2"
[165] "mpayroll_sobre_edad_lag2"
[166] "internet_delta1"
[167] "internet_delta2"
[168] "cliente_edad_delta1"
[169] "cliente_edad_delta2"
[170] "cliente_antiguedad_delta1"
[171] "cliente_antiguedad_delta2"
[172] "mrentabilidad_delta1"
[173] "mrentabilidad_delta2"
[174] "mrentabilidad_annual_delta1"
[175] "mrentabilidad_annual_delta2"
[176] "mcomisiones_delta1"
[177] "mcomisiones_delta2"
[178] "mactivos_margen_delta1"
[179] "mactivos_margen_delta2"
[180] "mpasivos_margen_delta1"
[181] "mpasivos_margen_delta2"
[182] "cproductos_delta1"
[183] "cproductos_delta2"
[184] "mcuenta_corriente_delta1"
[185] "mcuenta_corriente_delta2"
[186] "mcaja_ahorro_delta1"
[187] "mcaja_ahorro_delta2"
[188] "cdescubierto_preacordado_delta1"
[189] "cdescubierto_preacordado_delta2"
[190] "mcuentas_saldo_delta1"
[191] "mcuentas_saldo_delta2"
[192] "ctarjeta_visa_delta1"
[193] "ctarjeta_visa_delta2"
[194] "ctarjeta_visa_transacciones_delta1"
[195] "ctarjeta_visa_transacciones_delta2"
[196] "mtarjeta_visa_consumo_delta1"
[197] "mtarjeta_visa_consumo_delta2"
[198] "ctarjeta_master_delta1"
[199] "ctarjeta_master_delta2"
[200] "ctarjeta_master_transacciones_delta1"
[201] "ctarjeta_master_transacciones_delta2"
[202] "mtarjeta_master_consumo_delta1"
[203] "mtarjeta_master_consumo_delta2"
[204] "cprestamos_personales_delta1"
[205] "cprestamos_personales_delta2"
[206] "mprestamos_personales_delta1"
[207] "mprestamos_personales_delta2"
[208] "cpayroll_trx_delta1"
[209] "cpayroll_trx_delta2"
[210] "mpayroll_delta1"
[211] "mpayroll_delta2"
[212] "mttarjeta_visa_debitos_automaticos_delta1"
[213] "mttarjeta_visa_debitos_automaticos_delta2"
[214] "ccomisiones_mantenimiento_delta1"
[215] "ccomisiones_mantenimiento_delta2"
[216] "mcomisiones_mantenimiento_delta1"
[217] "mcomisiones_mantenimiento_delta2"
[218] "ccomisiones_otras_delta1"
[219] "ccomisiones_otras_delta2"
[220] "mtransferencias_recibidas_delta1"
[221] "mtransferencias_recibidas_delta2"
[222] "ccallcenter_transacciones_delta1"
[223] "ccallcenter_transacciones_delta2"
[224] "thomebanking_delta1"
[225] "thomebanking_delta2"
[226] "chomebanking_transacciones_delta1"
[227] "chomebanking_transacciones_delta2"
[228] "ctrx_quarter_delta1"
[229] "ctrx_quarter_delta2"
[230] "Master_status_delta1"
[231] "Master_status_delta2"
[232] "Master_mfinanciacion_limite_delta1"
[233] "Master_mfinanciacion_limite_delta2"
[234] "Master_Fvencimiento_delta1"
[235] "Master_Fvencimiento_delta2"
[236] "Master_msaldototal_delta1"
[237] "Master_msaldototal_delta2"
[238] "Master_mlimitecompra_delta1"
[239] "Master_mlimitecompra_delta2"
[240] "Master_fultimo_cierre_delta1"
[241] "Master_fultimo_cierre_delta2"
[242] "Master_fechaalta_delta1"
[243] "Master_fechaalta_delta2"
[244] "Master_mconsumototal_delta1"
[245] "Master_mconsumototal_delta2"
[246] "Master_cconsumos_delta1"
[247] "Master_cconsumos_delta2"
[248] "Master_mpagominimo_delta1"
[249] "Master_mpagominimo_delta2"
[250] "Visa_status_delta1"
[251] "Visa_status_delta2"
[252] "Visa_mfinanciacion_limite_delta1"
[253] "Visa_mfinanciacion_limite_delta2"
[254] "Visa_Fvencimiento_delta1"
[255] "Visa_Fvencimiento_delta2"
[256] "Visa_msaldototal_delta1"
[257] "Visa_msaldototal_delta2"
[258] "Visa_mlimitecompra_delta1"
[259] "Visa_mlimitecompra_delta2"
[260] "Visa_fultimo_cierre_delta1"
[261] "Visa_fultimo_cierre_delta2"
[262] "Visa_fechaalta_delta1"
[263] "Visa_fechaalta_delta2"
[264] "Visa_mconsumototal_delta1"
[265] "Visa_mconsumototal_delta2"
[266] "Visa_cconsumos_delta1"
[267] "Visa_cconsumos_delta2"
[268] "Visa_mpagominimo_delta1"
[269] "Visa_mpagominimo_delta2"
[270] "kmes_delta1"
[271] "kmes_delta2"
[272] "mpayroll_sobre_edad_delta1"
[273] "mpayroll_sobre_edad_delta2"

#### 9.3.1.6  FEhist Reduccion dimensionalidad con canaritos

Esta etapa solo se mostrará a la *modalidad Anlista Sr* por algun canal secreto de forma de no confundir a los *Analista Jr*  ni distraer con detalles operativos a la estratégica *Modalidad Gerencial*

In [ ]:
# No se implementa la reduccion de la dimensionalidad con canaritos

### 9.3.2 Modelado

#### 9.3.2.1 Training Strategy

Se hace una estrategia de entrenamiento muy sencilla, tomando todos los meses posibles, SIN eliminar nada x pandemia ni por ningun otro motivo

* future = 202109  obviamente completo

* final_train =  [ 201901, 202107 ]  SIN undersampling

* training
   * testing = NO HAY
   * validation =  202105   completo, sin undersampling
   * training = [ 201901, 202103 ]  donde se consideran el 100% de los CONTINUA

In [31]:
PARAM$trainingstrategy$validate <- c(202105)

PARAM$trainingstrategy$training <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103
)


PARAM$trainingstrategy$training_pct <- 1.0


PARAM$trainingstrategy$positivos <- c( "BAJA+1", "BAJA+2")

In [32]:
# seteo la clase01   1={BAJA+1, BAJA+2}   0={CONTINUA}
dataset[, clase01 := ifelse( clase_ternaria %in% PARAM$trainingstrategy$positivos, 1, 0 )]

In [33]:
# los campos en los que se entrena
campos_buenos <- copy( setdiff(
    colnames(dataset), c("clase_ternaria","clase01","azar"))
)

####  9.3.2.2. Hyperparameter Tuning

* Clase binaria que se optimiza :  positivos = [ BAJA+1, BAJA+2 ]

* Metrica que se optimiza **AUC** Area Under Curve de la  ROC Curve

es muy importante notar que intencionalmente  **NO** se está optimizando la funcion de ganancia del problema

* Parametros no default, fijos de LightGBM que no se optimizan
  * max_bin = 31 , Alienigenas Ancestrales contruyeron las pirámides y dejaron a la humanidad en un jeroglifico  *max_bin=31*
  * feature_fraction = 0.5  para poner algo que generalmente no falla
  * learning_rate = 0.03  para que aprenda lento

* Parametros que se optimizan en el Grid Search
  * num_leaves  [64, 512]
  * min_data_in_leaf  [64, 2048]

In [34]:
# parametros fijos del LightGBM
PARAM$lgbm$param_fijos <- list(
  objective= "binary",
  metric= "auc",
  first_metric_only= TRUE,
  boost_from_average= TRUE,
  feature_pre_filter= FALSE,
  verbosity= -100,
  force_row_wise= TRUE, # para evitar warning
  max_bin= 31,
  learning_rate= 0.03,
  feature_fraction= 0.5,
  num_iterations= 2048,  # valor grande, lo limita early_stopping_rounds
  early_stopping_rounds= 200,
  num_leaves= 64,
  min_data_in_leaf= 128
)

In [35]:
# En  x llegan los parametros moviles de LightGBM
#  devuelve la AUC en validate del modelo entrenado
#  en el parametro x llegan los hiperparámetros que se estan optimizando

Estimar_AUC_lightgbm <- function(x, dtrain, dvalidate) {

  # x pisa (o agrega) a param_fijos
  param_completo <- modifyList(PARAM$lgbm$param_fijos, x)
  param_completo$seed <- PARAM$semilla_primigenia

  # entreno LightGBM
  modelo_train <- lgb.train(
    data= dtrain,
    valids= list(valid = dvalidate),
    eval= "auc",
    param= param_completo,
    verbose= -100
  )

  # recupero la AUC en validation
  AUC <- modelo_train$record_evals$valid$auc$eval[[modelo_train$best_iter]]

  message(format(Sys.time(), "%a %b %d %X %Y  "),
    toString(x),
    " niter ", modelo_train$best_iter,
    " AUC ", AUC
  )

  # hago espacio en la memoria
  niter <- modelo_train$best_iter
  rm(modelo_train)
  gc(full= TRUE, verbose= FALSE)

  return( list(AUC, niter))
}

seteo del Grid Search

In [36]:
# lo que sigue a continuacion es una forma alternativa a los loops anidados
# creo una tabla con el producto cartesiano de los vectores
tb_nueva <- CJ(
  num_leaves= c(256, 384, 512),
  min_data_in_leaf= c(64, 256, 512),
  feature_fraction= c(0.5, 0.8)
)

Corrida del Grid Search,  aqui se hace el trabajo pesado
<br> por favor no se asuste con los warnings que pudieran aparecer
<br> ATENCION, la siguiente celda demora 60 minutos en Colab
<br> lamento profundamente tal intolerable espera gerencial

In [37]:
if(!require("lightgbm")) install.packages("lightgbm")
require("lightgbm")

Loading required package: lightgbm

In [38]:
lista_mejores <- list()
tb_grid_base <- copy(tb_nueva)

for (i in seq_along(PARAM$semillas)) {
  
  PARAM$semilla_primigenia <- PARAM$semillas[i]
  cat("Grid Search para semilla:", PARAM$semilla_primigenia, "(", i, "de", length(PARAM$semillas), ")\n")
  
  
  # dtrain
  set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
  dataset[, azar := runif(nrow(dataset))]
  
  # undersampling de los CONTINUA
  dataset[, fold_train :=  foto_mes %in% PARAM$trainingstrategy$training &
            (clase_ternaria %in% c("BAJA+1", "BAJA+2") |
               azar < PARAM$trainingstrategy$training_pct) ]
  
  dtrain <- lgb.Dataset(
    data = data.matrix(dataset[fold_train == TRUE, campos_buenos, with = FALSE]),
    label = dataset[fold_train == TRUE, clase01],
    free_raw_data = TRUE
  )

  cat("Semilla primigenia: ", PARAM$semilla_primigenia)
  cat("Hash:", digest::digest(dataset[fold_train == TRUE, azar]), "\n")
  
  dvalidate <- lgb.Dataset(
    data= data.matrix(dataset[foto_mes %in% PARAM$trainingstrategy$validate, campos_buenos, with = FALSE]),
    label= dataset[foto_mes %in% PARAM$trainingstrategy$validate, clase01],
    free_raw_data= TRUE,
    reference = dtrain
  )
    
  tb_iteracion <- copy(tb_grid_base)
  tb_iteracion[, c("AUC", "num_iterations") := Estimar_AUC_lightgbm(.SD, dtrain, dvalidate), by = 1:nrow(tb_iteracion)]
  
  # 1 txt por semilla  
  nombre_archivo <- sprintf("tb_grid_search_%02d.txt", i)
  fwrite( 
    tb_iteracion,
    file = nombre_archivo,
    sep = "\t",
    append = FALSE
  )
  
  # resultados
  setorder(tb_iteracion, -AUC)
  mejor_configuracion <- tb_iteracion[1]
  mejor_configuracion[, semilla_utilizada := PARAM$semilla_primigenia]
  
  lista_mejores[[i]] <- mejor_configuracion
  
  #limpieza de memoria
  rm(dtrain, dvalidate)
  gc() 
}

# consolidación de resultados en tabla
tb_mejores_por_semilla <- rbindlist(lista_mejores)
PARAM$out$lgbm$mejores_hiperparametros <- tb_mejores_por_semilla

print(PARAM$out$lgbm$mejores_hiperparametros)

Grid Search para semilla: 100019 ( 1 de 5 )
Semilla primigenia:  100019Hash: cbe3e3757632f3d6c8713f4c46e4266d

Sat Jul 18 02:52:47 2026  256, 64, 0.5 niter 306 AUC 0.926901850174786

Sat Jul 18 02:53:36 2026  256, 64, 0.8 niter 219 AUC 0.926069244636782

Sat Jul 18 02:54:56 2026  256, 256, 0.5 niter 277 AUC 0.926912143005829

Sat Jul 18 02:55:44 2026  256, 256, 0.8 niter 187 AUC 0.927194581362141

Sat Jul 18 02:56:44 2026  256, 512, 0.5 niter 167 AUC 0.927588474179972

Sat Jul 18 02:57:32 2026  256, 512, 0.8 niter 164 AUC 0.928395693295142

Sat Jul 18 02:59:12 2026  384, 64, 0.5 niter 376 AUC 0.926455494643503

Sat Jul 18 03:00:11 2026  384, 64, 0.8 niter 194 AUC 0.926106152885411

Sat Jul 18 03:01:28 2026  384, 256, 0.5 niter 224 AUC 0.926184578112986

Sat Jul 18 03:02:22 2026  384, 256, 0.8 niter 139 AUC 0.927267629737679

Sat Jul 18 03:03:30 2026  384, 512, 0.5 niter 158 AUC 0.927322320004117

Sat Jul 18 03:04:40 2026  384, 512, 0.8 niter 216 AUC 0.926490213745231

Sat Jul 18 03:06:21 2026  512, 64, 0.5 niter 314 AUC 0.924364360073955

Sat Jul 18 03:07:26 2026  512, 64, 0.8 niter 178 AUC 0.924916639590376

Sat Jul 18 03:09:34 2026  512, 256, 0.5 niter 440 AUC 0.924901968465531

Sat Jul 18 03:10:39 2026  512, 256, 0.8 niter 152 AUC 0.9255491878265

Sat Jul 18 03:12:06 2026  512, 512, 0.5 niter 207 AUC 0.924572367435633

Sat Jul 18 03:13:13 2026  512, 512, 0.8 niter 159 AUC 0.925490119266259

Grid Search para semilla: 500029 ( 2 de 5 )
Semilla primigenia:  500029Hash: 7e672695f48aee6beb34b33553d837ba

Sat Jul 18 03:14:18 2026  256, 64, 0.5 niter 178 AUC 0.929262902716616

Sat Jul 18 03:15:11 2026  256, 64, 0.8 niter 249 AUC 0.926572940454436

Sat Jul 18 03:16:10 2026  256, 256, 0.5 niter 131 AUC 0.928496701301275

Sat Jul 18 03:16:49 2026  256, 256, 0.8 niter 112 AUC 0.925354622594915

Sat Jul 18 03:17:45 2026  256, 512, 0.5 niter 135 AUC 0.928572975788035

Sat Jul 18 03:18:34 2026  256, 512, 0.8 niter 164 AUC 0.928793810782432

Sat Jul 18 03:19:43 2026  384, 64, 0.5 niter 194 AUC 0.926832027910471

Sat Jul 18 03:20:43 2026  384, 64, 0.8 niter 208 AUC 0.926854764313372

Sat Jul 18 03:21:50 2026  384, 256, 0.5 niter 176 AUC 0.926749531637781

Sat Jul 18 03:23:02 2026  384, 256, 0.8 niter 267 AUC 0.923441845888667

Sat Jul 18 03:24:06 2026  384, 512, 0.5 niter 143 AUC 0.927888963396696

Sat Jul 18 03:25:13 2026  384, 512, 0.8 niter 204 AUC 0.927587014748705

Sat Jul 18 03:26:22 2026  512, 64, 0.5 niter 152 AUC 0.925231953556288

Sat Jul 18 03:27:30 2026  512, 64, 0.8 niter 205 AUC 0.927423020761562

Sat Jul 18 03:29:31 2026  512, 256, 0.5 niter 416 AUC 0.927794714861696

Sat Jul 18 03:30:43 2026  512, 256, 0.8 niter 194 AUC 0.924860259456154

Sat Jul 18 03:31:58 2026  512, 512, 0.5 niter 166 AUC 0.926677558632651

Sat Jul 18 03:33:13 2026  512, 512, 0.8 niter 207 AUC 0.92677764489272

Grid Search para semilla: 777977 ( 3 de 5 )
Semilla primigenia:  777977Hash: 0e1d22bf8cfb6884525669f08f098ee0

Sat Jul 18 03:34:21 2026  256, 64, 0.5 niter 196 AUC 0.926278135338438

Sat Jul 18 03:35:16 2026  256, 64, 0.8 niter 280 AUC 0.926408255157745

Sat Jul 18 03:36:20 2026  256, 256, 0.5 niter 163 AUC 0.92631300806451

Sat Jul 18 03:37:09 2026  256, 256, 0.8 niter 184 AUC 0.926166143191715

Sat Jul 18 03:38:03 2026  256, 512, 0.5 niter 129 AUC 0.929065418622497

Sat Jul 18 03:38:49 2026  256, 512, 0.8 niter 147 AUC 0.927735569489284

Sat Jul 18 03:39:55 2026  384, 64, 0.5 niter 172 AUC 0.924400692231294

Sat Jul 18 03:41:00 2026  384, 64, 0.8 niter 242 AUC 0.925925644281295

Sat Jul 18 03:42:04 2026  384, 256, 0.5 niter 153 AUC 0.926335821279583

Sat Jul 18 03:43:01 2026  384, 256, 0.8 niter 155 AUC 0.925828092822901

Sat Jul 18 03:44:17 2026  384, 512, 0.5 niter 177 AUC 0.928428492092571

Sat Jul 18 03:45:13 2026  384, 512, 0.8 niter 130 AUC 0.926486142700117

Sat Jul 18 03:46:36 2026  512, 64, 0.5 niter 217 AUC 0.924723610602231

Sat Jul 18 03:47:39 2026  512, 64, 0.8 niter 174 AUC 0.925593892510583

Sat Jul 18 03:48:53 2026  512, 256, 0.5 niter 171 AUC 0.923798792051784

Sat Jul 18 03:49:57 2026  512, 256, 0.8 niter 157 AUC 0.924771618209708

Sat Jul 18 03:51:15 2026  512, 512, 0.5 niter 179 AUC 0.927708147543892

Sat Jul 18 03:52:50 2026  512, 512, 0.8 niter 309 AUC 0.928104498351227

Grid Search para semilla: 778777 ( 4 de 5 )
Semilla primigenia:  778777Hash: 6e4c35a8ade795f55387491676a70db8

Sat Jul 18 03:53:59 2026  256, 64, 0.5 niter 203 AUC 0.925383043098542

Sat Jul 18 03:54:46 2026  256, 64, 0.8 niter 204 AUC 0.925917118130207

Sat Jul 18 03:55:47 2026  256, 256, 0.5 niter 183 AUC 0.925838846526976

Sat Jul 18 03:56:30 2026  256, 256, 0.8 niter 155 AUC 0.929215432794342

Sat Jul 18 03:57:28 2026  256, 512, 0.5 niter 157 AUC 0.928989374572252

Sat Jul 18 03:58:12 2026  256, 512, 0.8 niter 142 AUC 0.929858197049337

Sat Jul 18 03:59:28 2026  384, 64, 0.5 niter 238 AUC 0.926210847875798

Sat Jul 18 04:00:25 2026  384, 64, 0.8 niter 175 AUC 0.925570157549446

Sat Jul 18 04:01:32 2026  384, 256, 0.5 niter 163 AUC 0.926804836401595

Sat Jul 18 04:02:27 2026  384, 256, 0.8 niter 139 AUC 0.928420810875375

Sat Jul 18 04:03:32 2026  384, 512, 0.5 niter 136 AUC 0.929439570712133

Sat Jul 18 04:04:28 2026  384, 512, 0.8 niter 145 AUC 0.928215491939715

Sat Jul 18 04:05:56 2026  512, 64, 0.5 niter 260 AUC 0.926922282212528

Sat Jul 18 04:06:56 2026  512, 64, 0.8 niter 156 AUC 0.926518480624514

Sat Jul 18 04:08:33 2026  512, 256, 0.5 niter 282 AUC 0.927951872565534

Sat Jul 18 04:09:41 2026  512, 256, 0.8 niter 183 AUC 0.926811211811869

Sat Jul 18 04:10:49 2026  512, 512, 0.5 niter 130 AUC 0.928030605041797

Sat Jul 18 04:11:59 2026  512, 512, 0.8 niter 171 AUC 0.926938796829501

Grid Search para semilla: 999961 ( 5 de 5 )
Semilla primigenia:  999961Hash: b3a88038b755e46604313787206e4a1e

Sat Jul 18 04:13:09 2026  256, 64, 0.5 niter 218 AUC 0.925021718641623

Sat Jul 18 04:13:59 2026  256, 64, 0.8 niter 221 AUC 0.927124375036966

Sat Jul 18 04:14:59 2026  256, 256, 0.5 niter 179 AUC 0.928925620469522

Sat Jul 18 04:15:42 2026  256, 256, 0.8 niter 141 AUC 0.927323702623213

Sat Jul 18 04:16:49 2026  256, 512, 0.5 niter 214 AUC 0.927992659828847

Sat Jul 18 04:17:34 2026  256, 512, 0.8 niter 147 AUC 0.930298945292067

Sat Jul 18 04:18:59 2026  384, 64, 0.5 niter 299 AUC 0.923275240287677

Sat Jul 18 04:19:58 2026  384, 64, 0.8 niter 211 AUC 0.924394931318396

Sat Jul 18 04:21:08 2026  384, 256, 0.5 niter 191 AUC 0.926390588358194

Sat Jul 18 04:22:04 2026  384, 256, 0.8 niter 158 AUC 0.928952581541881

Sat Jul 18 04:23:14 2026  384, 512, 0.5 niter 179 AUC 0.927373937783677

Sat Jul 18 04:24:08 2026  384, 512, 0.8 niter 126 AUC 0.927914849098648

Sat Jul 18 04:25:33 2026  512, 64, 0.5 niter 243 AUC 0.924005647230883

Sat Jul 18 04:26:39 2026  512, 64, 0.8 niter 190 AUC 0.924882458173852

Sat Jul 18 04:27:44 2026  512, 256, 0.5 niter 131 AUC 0.927105709679179

Sat Jul 18 04:29:21 2026  512, 256, 0.8 niter 331 AUC 0.926673871648397

Sat Jul 18 04:31:11 2026  512, 512, 0.5 niter 344 AUC 0.926104309393284

Sat Jul 18 04:32:36 2026  512, 512, 0.8 niter 250 AUC 0.925830550812404

   num_leaves min_data_in_leaf feature_fraction       AUC num_iterations
        <num>            <num>            <num>     <num>          <int>
1:        256              512              0.8 0.9283957            164
2:        256               64              0.5 0.9292629            178
3:        256              512              0.5 0.9290654            129
4:        256              512              0.8 0.9298582            142
5:        256              512              0.8 0.9302989            147
   semilla_utilizada
               <num>
1:            100019
2:            500029
3:            777977
4:            778777
5:            999961

In [39]:
resultados_finales <- list()

PARAM$trainingstrategy$final_train <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105
)
dataset[, fold_final_train := foto_mes %in% as.character(PARAM$trainingstrategy$final_train)]

PARAM$trainingstrategy$future <- c(202107)
dfuture <- dataset[ foto_mes %in% PARAM$trainingstrategy$future ]

for (i in seq_len(nrow(PARAM$out$lgbm$mejores_hiperparametros))) {
  fila <- PARAM$out$lgbm$mejores_hiperparametros[i]
  PARAM$semilla_primigenia <- fila$semilla_utilizada
  cat("Modelo final semilla:", PARAM$semilla_primigenia, "(", i, "de", nrow(PARAM$out$lgbm$mejores_hiperparametros), ")\n")

  # dfinal_train
  dfinal_train <- lgb.Dataset(
    data= data.matrix(dataset[fold_final_train == TRUE, campos_buenos, with= FALSE]),
    label= dataset[fold_final_train == TRUE, clase01],
    free_raw_data= FALSE
  )

  # armo param_final para esta semilla
  fijos <- copy(PARAM$lgbm$param_fijos)
  fijos$num_iterations <- NULL
  fijos$early_stopping_rounds <- NULL
  fijos$seed <- PARAM$semilla_primigenia

  param_final <- c(
    fijos,
    list(
      num_leaves = fila$num_leaves,
      min_data_in_leaf = fila$min_data_in_leaf,
      feature_fraction = fila$feature_fraction,
      num_iterations = fila$num_iterations
    )
  )

  # entreno
  set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
  final_model <- lgb.train(
    data= dfinal_train,
    param= param_final,
    verbose= -100
  )

  lgb.save(final_model, sprintf("modelo_%02d.txt", i))

  # importancia
  tb_importancia <- as.data.table(lgb.importance(final_model))
  fwrite(tb_importancia, file= sprintf("impo_%02d.txt", i), sep= "\t")

  # prediccion
  dfuture <- dataset[foto_mes %in% PARAM$trainingstrategy$future]

  prediccion <- predict(
    final_model,
    data.matrix(dfuture[, campos_buenos, with= FALSE])
  )

  tb_prediccion <- dfuture[, list(numero_de_cliente, clase_ternaria)]
  tb_prediccion[, prob := prediccion]

  fwrite(tb_prediccion, file= sprintf("prediccion_%02d.txt", i), sep= "\t")

  tb_prediccion[, clase_ternaria := dfuture$clase_ternaria]
  tb_prediccion[, ganancia := -0.025]
  tb_prediccion[clase_ternaria=="BAJA+2", ganancia := 0.975]

  setorder(tb_prediccion, -prob)
  tb_prediccion[, gan_acum := cumsum(ganancia)]
  tb_prediccion[, gan_suavizada := frollmean(
    x= gan_acum, n= 400, align= "center", na.rm= TRUE, has.nf= TRUE
  )]

  resultado <- list()
  resultado$semilla <- PARAM$semilla_primigenia
  resultado$ganancia_suavizada_max <- max(tb_prediccion$gan_suavizada, na.rm= TRUE)
  resultado$envios <- which.max(tb_prediccion$gan_suavizada)

  fwrite(tb_prediccion, file= sprintf("ganancias_%02d.txt", i), sep= "\t")

  tb_prediccion[, envios := .I]

  pdf(sprintf("curva_de_ganancia_%02d.pdf", i))
  plot(
    x= tb_prediccion$envios,
    y= tb_prediccion$gan_acum,
    type= "l",
    col= "gray",
    xlim= c(0, 10000),
    ylim= c(0, 15000000),
    main= paste0("Semilla ", PARAM$semilla_primigenia, " | gan prom= ",
                 as.integer(resultado$ganancia_suavizada_max),
                 " envios= ", resultado$envios),
    xlab= "Envios",
    ylab= "Ganancia",
    panel.first= grid()
  )
  dev.off()

  resultados_finales[[i]] <- as.data.table(resultado)

  rm(dfinal_train, final_model)
  gc()
}

tb_resultados_finales <- rbindlist(resultados_finales)
PARAM$resultado <- tb_resultados_finales

require("yaml")
write_yaml(PARAM, file= "PARAM.yml")

print(tb_resultados_finales)

Modelo final semilla: 100019 ( 1 de 5 )
Modelo final semilla: 500029 ( 2 de 5 )
Modelo final semilla: 777977 ( 3 de 5 )
Modelo final semilla: 778777 ( 4 de 5 )
Modelo final semilla: 999961 ( 5 de 5 )

Loading required package: yaml

   semilla ganancia_suavizada_max envios
     <num>                  <num>  <int>
1:  100019                92.3225   2240
2:  500029                91.2875   2242
3:  777977                94.7350   2292
4:  778777                95.2150   2467
5:  999961                91.8750   1819

la optimizacion de hiperparámetros de tipo  Grid Search ha corrido, extraigo los mejores hiperparametros

### 9.3.3 Produccion

#### Final Training
Construyo el modelo final, que es uno solo, no hace ningun tipo de particion < training, validation, testing>]

##### Final Training Dataset

Aqui esta la gran decision de en qué meses hago el Final Training
<br> debo utilizar los mejores hiperparámetros que encontré en la optimización bayesiana

In [ ]:
PARAM$trainingstrategy$final_train <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105
)


dataset[, fold_final_train := foto_mes %in% PARAM$trainingstrategy$final_train ]

# creo el dfinal_train en formato  LightGBM
dfinal_train <- lgb.Dataset(
  data= data.matrix(dataset[fold_final_train == TRUE, campos_buenos, with= FALSE]),
  label= dataset[fold_final_train == TRUE, clase01],
  free_raw_data= TRUE
)

nrow( dfinal_train) # verifico el tamaño

##### Final Training Hyperparameters

In [ ]:
# uno los parametros fijos y los mejores encontrados de los variables
fijos <- copy(PARAM$lgbm$param_fijos)

# quito lo que optimice en la Bayesian Optimization
fijos$num_iterations <- NULL
fijos$early_stopping_rounds <- NULL

# agrego a los hiperparametros fijos los que encontre con la Bayesian Optimization
param_final <- c(fijos, PARAM$out$lgbm$mejores_hiperparametros)

##### Training
Genero el modelo final, siempre sobre TODOS los datos de  final_train, sin hacer ningun tipo de undersampling de la clase mayoritaria

In [ ]:
final_model <- lgb.train(
  data= dfinal_train,
  param= param_final,
  verbose= -100
)

In [ ]:
# grabo a disco el modelo en un formato para seres humanos ... ponele ...

lgb.save(final_model, "modelo.txt")

In [ ]:
# ahora imprimo la importancia de variables

tb_importancia <- as.data.table(lgb.importance(final_model))
archivo_importancia <- "impo.txt"

fwrite( tb_importancia,
  file= archivo_importancia,
  sep= "\t"
)

#### Scoring

Aplico el modelo final a los datos del futuro

In [ ]:
PARAM$trainingstrategy$future <- c(202107)

dfuture <- dataset[ foto_mes %in% PARAM$trainingstrategy$future ]

In [ ]:
# aplico final_model   a dfuture

prediccion <- predict(
  final_model,
  data.matrix(dfuture[, campos_buenos, with= FALSE])
)

##### Tabla Prediccion

In [ ]:
tb_prediccion <- dfuture[, list(numero_de_cliente, clase_ternaria)]
tb_prediccion[, prob := prediccion]

# grabo las probabilidad del modelo
#  me va a ser util para hacer Ensembles de modelos
fwrite(tb_prediccion,
  file= "prediccion.txt",
  sep= "\t"
)

#### Curva de Ganancia

Genero las salidas

In [ ]:
# asigno clase ternaria
tb_prediccion[, clase_ternaria := dfuture$clase_ternaria ]

# asigno ganancias
tb_prediccion[, ganancia := -0.025 ]
tb_prediccion[clase_ternaria=="BAJA+2", ganancia := 0.975 ]

# reordeno, y acumulada
setorder( tb_prediccion, -prob )
tb_prediccion[, gan_acum := cumsum(ganancia)]

# media movil de ancho 400
tb_prediccion[,
  gan_suavizada := frollmean(
    x= gan_acum,
    n= 400,
    align= "center",
    na.rm= TRUE,
    hasNA= TRUE
  )
]

In [ ]:
tb_prediccion[, sum(!is.na(gan_suavizada) )]
tb_prediccion[, .N]

In [ ]:
# Este es la ganancia a reportar
resultado <- list()
resultado$ganancia_suavizada_max <- max( tb_prediccion$gan_suavizada, na.rm=TRUE )
options(digits= 8)
resultado$envios <- which.max( tb_prediccion$gan_suavizada)
resultado

In [ ]:
# grabo las ganancias
fwrite( tb_prediccion,
  file= "ganancias.txt",
  sep= "\t"
)

In [ ]:
# genero el grafico

tb_prediccion[, envios:= .I]

pdf("curva_de_ganancia.pdf")

plot(
  x= tb_prediccion$envios,
  y= tb_prediccion$gan_acum,
  type= "l",
  col= "gray",
  xlim= c(0, 10000),
  ylim= c(0, 15000000),
  main= paste0("Mejor gan prom= ", as.integer(resultado$ganancia_suavizada_max), " envios= ", resultado$envios),
  xlab= "Envios",
  ylab= "Ganancia",
  panel.first= grid()
)

dev.off()

In [ ]:
# grabo los parametros
if( !require("yaml")) install.packages("yaml")
require("yaml")

PARAM$resultado <- resultado

write_yaml( PARAM, file="PARAM.yml")

In [ ]:
format(Sys.time(), "%a %b %d %X %Y")